# Site Settings
title: My Resume
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar

# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: # blue turquoise green berry orange ceramic mdc

# Profile information
name: Alan Doe
tagline: Full Stack Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
pic-info: This is a profile picture # An helpful information about the image
summary: 'Summarise your career here lorem ipsum dolor sit amet, consectetuer adipiscing elit.
You can <a href="#" target="_blank">download this free resume/CV template here</a>. Aenean
commodo ligula eget dolor aenean massa. Cum sociis natoque penatibus et magnis dis parturient
montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu.'

# Sidebar links
# email: hello@webjeda.com

# Insert the email clobbered using (the power of) HTML entities:
#
#   1. Either do it manually: https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references
#
#      or
#
#   2. Use the power of Markdown to create it: https://daringfireball.net/projects/markdown/syntax#autolink
#
# The example was created using the power of Markdown.
#
# Note: Either specify `email` or `clobbered_email`. If both are specified `clobbered_email` is used.
#
clobbered_email: "&#104;&#x65;&#108;&#108;&#x6F;&#64;&#x77;&#x65;&#98;&#x6A;&#101;&#x64;&#97;&#x2E;&#x63;&#111;&#x6D;"

# You could also specify a clobbered version of your name to be used in the link to email you
#
# If unspecified only the clobbered email will be used in the link
clobbered_name: "&#65;&#x6C;&#97;&#x6E;&#32&#68;&#x6F;&#101;"

phone: 012 345 6789
location: Earth
website: blog.webjeda.com #do not add http://
linkedin: alandoe
github: sharu725
twitter: '@webjeda'
wikipedia-en: Jimmy Wales # without the 'User:' prefix

# Update all the sections by editing the files inside _data folder.

# uncomment the next lines, if you want the education/cetification sections displayed
# in main instead of the sidebar
# education_in_main: True
# certification_in_main: True

# Tracker
analytics: UA-83979019-1

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
