# Site Settings
title: Kaartic Sivaraam's Résumé
url: 'https://sivaraam.github.io/'

# Note: a leading slash in the baseurl makes it impossible for
# wkhtmltopdf to correctly locate the resource.
# This is possibly because the leading '/' doesn't have the same
# meaning of the root as in HTML.
baseurl: '.'

about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar

# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: mdc # blue turquoise green berry orange ceramic mdc

# Profile information
name: Kaartic Sivaraam
# tagline: Full Stack Developer
# pic: Lotus_flower.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
pic-info: By Hong Zhang (jennyzhh2008) [CC0 or CC0], via Wikimedia Commons
summary: 'I''m a developer seeking to work with awesome people.
A few things that best describe me:
  <ul>
    <li>
      <em>Semi-<abbr title="a self-taught person">autodidact</abbr></em>.
    </li>
    <li>
      Passionate about programming. Loves to craft eloquent programs.
    </li>
    <li>
      Loves to explore behind the scenes working of things.
    </li>
    <li>
      Interested in design.
    </li>
  </ul>
'

# Sidebar links
# email: kaartic.sivaraam@gmail.com

# Insert the email clobbered using (the power of) HTML entities:
#
#   1. Either do it manually: https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references
#
#      or
#
#   2. Use the power of Markdown to create it: https://daringfireball.net/projects/markdown/syntax#autolink
#
# The example was created using the power of Markdown.
#
# Note: Either specify `email` or `clobbered_email`. If both are specified `clobbered_email` is used.
#
clobbered_email: "&#104;&#x65;&#108;&#108;&#x6F;&#64;&#x77;&#x65;&#98;&#x6A;&#101;&#x64;&#97;&#x2E;&#x63;&#111;&#x6D;"

# You could also specify a clobbered version of your name to be used in the link to email you
#
# If unspecified only the clobbered email will be used in the link
clobbered_email: "&#107;&#97;&#x61;&#x72;&#x74;&#x69;&#99;&#x2E;&#x73;&#105;&#x76;&#x61;&#x72;&#97;&#97;&#109;&#64;&#103;&#109;&#x61;&#x69;&#x6C;&#x2E;&#x63;o&#x6D;"

location: Madurai, India
website: kaartics.wordpress.com #do not add http://
linkedin: kaartics
github: sivaraam
gitlab: sivaraam
medium: '@sivaraam'
wikipedia-en: Kaartic # without the 'User:' prefix
twitter: '@kaartics'

# Update all the sections by editing the files inside _data folder.

# uncomment the next lines, if you want the education/cetification sections displayed
# in main instead of the sidebar
education_in_main: True
# certification_in_main: True

# Tracker
# analytics: UA-83979019-1

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
