#! /bin/sh
#
# Script to generate the PDF version of Resume.

does_it_exist () {
	if (which $1 >/dev/null 2>/dev/null)
	then
		return 0
	else
		return 1
	fi
}

if !(does_it_exist jekyll)
then
	echo 'Jekyll is needed to generate the site'
	echo 'Visit https://jekyllrb.com/ for instructions about installing Jekyll'
	exit 1
fi

if !(does_it_exist wkhtmltopdf)
then
	echo 'wkhtmltopdf is required to generate the PDF from the site'
	echo 'Visit https://wkhtmltopdf.org/downloads.html for instructions'
	echo 'about downloading the binary.'
	echo "Note: There seems to be issues with 'wkhtmltopdf' installed via the package"
	echo "manager of some distributions which seems to use an unpatched version of Qt."
	echo "As a consequence the PDF is not generated as expected. So, it's better to use"
	echo "the package obtained from the website which seems to be using a patched version of Qt."
	exit 1
fi

echo 'Generating the site ..'
if (jekyll build >/dev/null)
then
	echo 'Successfully generated the site.'

	echo 'Generating the PDF file ..'

	# We request for '--no-outline' as current layout of the page (the sidebar, in particular)
	# tricks `wkhtmltopdf` into generating the outline with an incorrect nesting.
	#
	# So, it's better to generate the PDF without the outline for now.
	#
	# FIXME:
	#
	# Either,
	# 	1. Help wkhtmltopdf to fix the issues with sidebars (if there is one ;-)
	# 	2. Change the layout of the site to avoid this issue
	#
	# It would be nice to achieve the former.
	#
	if (wkhtmltopdf --no-outline --margin-bottom 20mm --margin-top 10mm --minimum-font-size 14 _site/index.html resume.pdf >/dev/null)
	then
		echo 'Successfully generate the PDF file.'
	else
		echo 'wkhtmltopdf returned failure code.'
		echo "It's fine if it failed with an 'UnknownNetworkError' as it shouldn't affect the generated file."
		echo "If it's something let me know. You know how to contact me ;-)"
	fi
else
	echo 'FATAL: Generating the site failed!'
fi

